### ISSUE TITLE
All Paths with Sum equal to 'K'

### ISSUE THREAD

**Issue by alan0428a** [backtobackswe/backtobackswe-feedback#9]
# Back To Back SWE
<br/> <br/>

## Create a bug report to help us improve our content -

<br/><br/>

#### Your email registered on BackToBackSWE  :
alan0428a@gmail.com

<br/><br/>

#### Category of the bug :
- [ ] Question
- [x] Solution
- [ ] Language

<br/><br/>

#### Description of the bug :

<br/><br/>

#### Code you used for Submit/Run operation :

```

class Solution {
  public:
    int pathSum(TreeNode* root, int sum) {
      unordered_map<int, int> map;
      map[0] = 1;
      
      return helper(root, sum, 0, map);
    }
    
    int helper(TreeNode *root, int target, int sum, unordered_map<int, int> &map)
    {
      if(!root) return 0;
      
      int count = 0;
      
      sum += root->value;
      
      if(map.find(sum - target) != map.end())
      {
        count += map[sum - target];
      }
      
      map[sum]++;
      
      count += helper(root->left, target, sum, map);
      count += helper(root->right, target, sum, map);
      
      map[sum]--;
      
      return count;
    }
};

```

<br/><br/>

#### Language used for code :
 C++

<br/><br/>

#### Expected behavior :

<br/><br/>

#### Screenshots :

<br/><br/>

#### Additional context :

<br/><br/>

**Comment by shubhankar-99** [comment]
Thank You for your contribution. We have added this solution on our website . You can find it at https://backtobackswe.com/platform/content/all-paths-with-sum/solutions
